# Generated by Django 6.0.7 on 2026-07-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('confederation', models.CharField(choices=[('UEFA', 'UEFA - Europe'), ('CONMEBOL', 'CONMEBOL - South America'), ('CONCACAF', 'CONCACAF - North America'), ('CAF', 'CAF - Africa'), ('AFC', 'AFC - Asia'), ('OFC', 'OFC - Oceania')], max_length=10)),
                ('flag_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F'), ('G', 'Group G'), ('H', 'Group H'), ('I', 'Group I'), ('J', 'Group J'), ('K', 'Group K'), ('L', 'Group L')], max_length=1)),
                ('badge_image', models.URLField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='app_panini.country')),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
    ]