# Generated by Django 6.0.7 on 2026-07-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_panini', '0002_alter_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('jersey_number', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['team', 'jersey_number'],
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app_panini.team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
    ]