# Generated by Django 6.0.7 on 2026-07-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panini', '0003_player_alter_country_flag_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.URLField(blank=True, help_text='URL de la imagen de la bandera', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.URLField(blank=True, help_text='URL de la imagen del jugador', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='badge_image',
            field=models.URLField(blank=True, help_text='URL de la imagen del escudo', null=True),
        ),
    ]