# Generated by Django 6.0.7 on 2026-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panini', '0004_alter_country_flag_image_alter_player_player_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]